CREATE TABLE "Account" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar NOT NULL,
  "Ballance" bigint NOT NULL,
  "Currency" varchar NOT NULL,
  "CreatedAt" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "Entries" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AccountNumber" bigint,
  "Amount" bigint NOT NULL,
  "CreatedAt" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "Transfers" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FromAccount" int NOT NULL,
  "ToAccount" int NOT NULL,
  "Amount" bigint NOT NULL,
  "CreatedAt" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE INDEX ON "Account" ("Id");

CREATE INDEX ON "Entries" ("AccountNumber");

CREATE INDEX ON "Transfers" ("FromAccount");

CREATE INDEX ON "Transfers" ("ToAccount");

CREATE INDEX ON "Transfers" ("FromAccount", "ToAccount");

COMMENT ON COLUMN "Entries"."Amount" IS 'Can be negative or positive';

COMMENT ON COLUMN "Transfers"."Amount" IS 'Must be positive';

ALTER TABLE "Entries" ADD FOREIGN KEY ("AccountNumber") REFERENCES "Account" ("Id");

ALTER TABLE "Transfers" ADD FOREIGN KEY ("FromAccount") REFERENCES "Account" ("Id");

ALTER TABLE "Transfers" ADD FOREIGN KEY ("ToAccount") REFERENCES "Account" ("Id");
